---
title: Un blog foodie.
author: David
date: '2020-06-01'
categories:
  - Blog
tags:
  - Bienvenido
  - Comida
  - Recetas
cover: /img/dkche.jpg
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Amamos la comida.

Conocemos lugares que sirven muy buena comida, de esos lugares que después de conocerlos queremos llevar a todos a probar, algunos cuestan lo justo y para otros tenemos que ahorrar (pero valen cada peso gastado).

Algunos otros lugares que hemos visitado no valen el precio y/o la experiencia; y claro, siempre que podemos, recomedamos otra opción.

Otros más son nuestro secreto (o eso creemos) y ahí llevamos a las personas que más nos importan (o que no nos caen mal :stuck_out_tongue_closed_eyes:).

Sí, nos encanta comer, pero no solo comer lo que algún maravilloso menú tiene por ofrecernos, también lo que nosotros mismos hacemos. 

Amamos cocinar y quizá más que salir a comer (excepto cuando nuestra receta no es tan buena, claro).

Quienes nos conocen nos llaman _foodies_ y creo que sí, así nos identificamos. 

Decidimos empezar este blog por amor a la comida, para contar nuestras historias alrededor de ella pero también para ayudar a quienes nos lean a encontrar un buen lugar para comer, y como al empezar este blog estamos en tiempos de coronavirus, también queremos compartir recetas que puedan hacer ustedes mismos; si ya cocinan pues para que, con suerte, encuentren otra receta más para su menú y si no cocinan, pues para que se animen, bastantes anecdotas sobre intentos fallidos al cocinar hemos escuchado, pero personalmente creo que eso puede cambiar y que cualquiera puede hacerse algo rico para consentirse :wink:.

La cubierta de este primer post fue tomada en un extinto restaurante (lamentablemente) de Coyoacán llamado dk-ché.